from __future__ import annotations

from typing import Protocol


class BasePowerSupply(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def set_voltage(self, value: float) -> None: ...
    def set_current_limit(self, value: float) -> None: ...
    def output_on(self) -> None: ...
    def output_off(self) -> None: ...
