from __future__ import annotations

from typing import Protocol


class BaseSwitch(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def list_paths(self): ...
    def select_path(self, path_name: str) -> None: ...
