from __future__ import annotations

from typing import Any, Dict, Protocol


class BaseAnalyzer(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def reset(self) -> None: ...
    def configure(self, settings: Dict[str, Any]) -> None: ...
    def get_trace(self) -> Dict[str, Any]: ...
